#! /usr/bin/env bash
cat \
      ./modules/header.html \
      ./modules/banner-top.html \
      ./modules/hello-nature-readers.html \
      ./modules/hero-image.html \
      ./modules/banner-news.html \
      ./modules/article-no-image.html \
      ./modules/horizontal-line.html \
      ./modules/article-no-image.html \
      ./modules/horizontal-line.html \
      ./modules/article-no-image.html \
      ./modules/breakthroughs-you-may-have-missed.html \
      ./modules/banner-features-and-analysis.html \
      ./modules/article-no-image.html \
      ./modules/horizontal-line.html\
      ./modules/article-no-image.html \
      ./modules/podcast.html \
      ./modules/banner-infographic-of-the-week.html \
      ./modules/article-column-width-image.html \
      ./modules/banner-scientific-life.html \
      ./modules/article-no-image.html \
      ./modules/horizontal-line.html \
      ./modules/article-no-image.html \
      ./modules/materials-and-methods.html \
      ./modules/banner-image-of-the-week.html \
      ./modules/article-full-width-image.html \
      ./modules/banner-books-and-arts.html \
      ./modules/article-no-image.html \
      ./modules/horizontal-line.html \
      ./modules/article-no-image.html \
      ./modules/the-last-word.html \
      ./modules/footer.html \
    > newsletter-template-b.html